#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanGiayChuyenNganh.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyBanGiayChuyenNganh")]
	public partial class dbShoesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHATLIEU(CHATLIEU instance);
    partial void UpdateCHATLIEU(CHATLIEU instance);
    partial void DeleteCHATLIEU(CHATLIEU instance);
    partial void InsertVAITRO(VAITRO instance);
    partial void UpdateVAITRO(VAITRO instance);
    partial void DeleteVAITRO(VAITRO instance);
    partial void InsertCTHOADON(CTHOADON instance);
    partial void UpdateCTHOADON(CTHOADON instance);
    partial void DeleteCTHOADON(CTHOADON instance);
    partial void InsertGIAY(GIAY instance);
    partial void UpdateGIAY(GIAY instance);
    partial void DeleteGIAY(GIAY instance);
    partial void InsertGIOITINH(GIOITINH instance);
    partial void UpdateGIOITINH(GIOITINH instance);
    partial void DeleteGIOITINH(GIOITINH instance);
    partial void InsertHOADON(HOADON instance);
    partial void UpdateHOADON(HOADON instance);
    partial void DeleteHOADON(HOADON instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertKIEUDANG(KIEUDANG instance);
    partial void UpdateKIEUDANG(KIEUDANG instance);
    partial void DeleteKIEUDANG(KIEUDANG instance);
    partial void InsertLOAIGIAY(LOAIGIAY instance);
    partial void UpdateLOAIGIAY(LOAIGIAY instance);
    partial void DeleteLOAIGIAY(LOAIGIAY instance);
    partial void InsertMAU(MAU instance);
    partial void UpdateMAU(MAU instance);
    partial void DeleteMAU(MAU instance);
    partial void InsertQUANTRI(QUANTRI instance);
    partial void UpdateQUANTRI(QUANTRI instance);
    partial void DeleteQUANTRI(QUANTRI instance);
    partial void InsertSIZE(SIZE instance);
    partial void UpdateSIZE(SIZE instance);
    partial void DeleteSIZE(SIZE instance);
    partial void InsertTAIKHOANKH(TAIKHOANKH instance);
    partial void UpdateTAIKHOANKH(TAIKHOANKH instance);
    partial void DeleteTAIKHOANKH(TAIKHOANKH instance);
    partial void InsertTHUONGHIEU(THUONGHIEU instance);
    partial void UpdateTHUONGHIEU(THUONGHIEU instance);
    partial void DeleteTHUONGHIEU(THUONGHIEU instance);
    partial void InsertTINHTRANGDONHANG(TINHTRANGDONHANG instance);
    partial void UpdateTINHTRANGDONHANG(TINHTRANGDONHANG instance);
    partial void DeleteTINHTRANGDONHANG(TINHTRANGDONHANG instance);
    #endregion
		
		public dbShoesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QuanLyBanGiayChuyenNganhConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbShoesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbShoesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbShoesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbShoesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHATLIEU> CHATLIEUs
		{
			get
			{
				return this.GetTable<CHATLIEU>();
			}
		}
		
		public System.Data.Linq.Table<VAITRO> VAITROs
		{
			get
			{
				return this.GetTable<VAITRO>();
			}
		}
		
		public System.Data.Linq.Table<CTHOADON> CTHOADONs
		{
			get
			{
				return this.GetTable<CTHOADON>();
			}
		}
		
		public System.Data.Linq.Table<GIAY> GIAYs
		{
			get
			{
				return this.GetTable<GIAY>();
			}
		}
		
		public System.Data.Linq.Table<GIOITINH> GIOITINHs
		{
			get
			{
				return this.GetTable<GIOITINH>();
			}
		}
		
		public System.Data.Linq.Table<HOADON> HOADONs
		{
			get
			{
				return this.GetTable<HOADON>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<KIEUDANG> KIEUDANGs
		{
			get
			{
				return this.GetTable<KIEUDANG>();
			}
		}
		
		public System.Data.Linq.Table<LOAIGIAY> LOAIGIAYs
		{
			get
			{
				return this.GetTable<LOAIGIAY>();
			}
		}
		
		public System.Data.Linq.Table<MAU> MAUs
		{
			get
			{
				return this.GetTable<MAU>();
			}
		}
		
		public System.Data.Linq.Table<QUANTRI> QUANTRIs
		{
			get
			{
				return this.GetTable<QUANTRI>();
			}
		}
		
		public System.Data.Linq.Table<SIZE> SIZEs
		{
			get
			{
				return this.GetTable<SIZE>();
			}
		}
		
		public System.Data.Linq.Table<TAIKHOANKH> TAIKHOANKHs
		{
			get
			{
				return this.GetTable<TAIKHOANKH>();
			}
		}
		
		public System.Data.Linq.Table<THUONGHIEU> THUONGHIEUs
		{
			get
			{
				return this.GetTable<THUONGHIEU>();
			}
		}
		
		public System.Data.Linq.Table<TINHTRANGDONHANG> TINHTRANGDONHANGs
		{
			get
			{
				return this.GetTable<TINHTRANGDONHANG>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHATLIEU")]
	public partial class CHATLIEU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaChatLieu;
		
		private string _TenChatLieu;
		
		private EntitySet<GIAY> _GIAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChatLieuChanging(int value);
    partial void OnMaChatLieuChanged();
    partial void OnTenChatLieuChanging(string value);
    partial void OnTenChatLieuChanged();
    #endregion
		
		public CHATLIEU()
		{
			this._GIAYs = new EntitySet<GIAY>(new Action<GIAY>(this.attach_GIAYs), new Action<GIAY>(this.detach_GIAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChatLieu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaChatLieu
		{
			get
			{
				return this._MaChatLieu;
			}
			set
			{
				if ((this._MaChatLieu != value))
				{
					this.OnMaChatLieuChanging(value);
					this.SendPropertyChanging();
					this._MaChatLieu = value;
					this.SendPropertyChanged("MaChatLieu");
					this.OnMaChatLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChatLieu", DbType="NVarChar(10)")]
		public string TenChatLieu
		{
			get
			{
				return this._TenChatLieu;
			}
			set
			{
				if ((this._TenChatLieu != value))
				{
					this.OnTenChatLieuChanging(value);
					this.SendPropertyChanging();
					this._TenChatLieu = value;
					this.SendPropertyChanged("TenChatLieu");
					this.OnTenChatLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHATLIEU_GIAY", Storage="_GIAYs", ThisKey="MaChatLieu", OtherKey="MaChatLieu")]
		public EntitySet<GIAY> GIAYs
		{
			get
			{
				return this._GIAYs;
			}
			set
			{
				this._GIAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.CHATLIEU = this;
		}
		
		private void detach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.CHATLIEU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VAITRO")]
	public partial class VAITRO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaVaiTro;
		
		private string _TenVaiTro;
		
		private EntitySet<TAIKHOANKH> _TAIKHOANKHs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaVaiTroChanging(int value);
    partial void OnMaVaiTroChanged();
    partial void OnTenVaiTroChanging(string value);
    partial void OnTenVaiTroChanged();
    #endregion
		
		public VAITRO()
		{
			this._TAIKHOANKHs = new EntitySet<TAIKHOANKH>(new Action<TAIKHOANKH>(this.attach_TAIKHOANKHs), new Action<TAIKHOANKH>(this.detach_TAIKHOANKHs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVaiTro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaVaiTro
		{
			get
			{
				return this._MaVaiTro;
			}
			set
			{
				if ((this._MaVaiTro != value))
				{
					this.OnMaVaiTroChanging(value);
					this.SendPropertyChanging();
					this._MaVaiTro = value;
					this.SendPropertyChanged("MaVaiTro");
					this.OnMaVaiTroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenVaiTro", DbType="NVarChar(50)")]
		public string TenVaiTro
		{
			get
			{
				return this._TenVaiTro;
			}
			set
			{
				if ((this._TenVaiTro != value))
				{
					this.OnTenVaiTroChanging(value);
					this.SendPropertyChanging();
					this._TenVaiTro = value;
					this.SendPropertyChanged("TenVaiTro");
					this.OnTenVaiTroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VAITRO_TAIKHOANKH", Storage="_TAIKHOANKHs", ThisKey="MaVaiTro", OtherKey="MaVaiTro")]
		public EntitySet<TAIKHOANKH> TAIKHOANKHs
		{
			get
			{
				return this._TAIKHOANKHs;
			}
			set
			{
				this._TAIKHOANKHs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TAIKHOANKHs(TAIKHOANKH entity)
		{
			this.SendPropertyChanging();
			entity.VAITRO = this;
		}
		
		private void detach_TAIKHOANKHs(TAIKHOANKH entity)
		{
			this.SendPropertyChanging();
			entity.VAITRO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTHOADON")]
	public partial class CTHOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaCTHD;
		
		private System.Nullable<int> _MaHoaDon;
		
		private System.Nullable<int> _MaGiay;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<double> _ThanhTien;
		
		private EntityRef<GIAY> _GIAY;
		
		private EntityRef<HOADON> _HOADON;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCTHDChanging(int value);
    partial void OnMaCTHDChanged();
    partial void OnMaHoaDonChanging(System.Nullable<int> value);
    partial void OnMaHoaDonChanged();
    partial void OnMaGiayChanging(System.Nullable<int> value);
    partial void OnMaGiayChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnThanhTienChanging(System.Nullable<double> value);
    partial void OnThanhTienChanged();
    #endregion
		
		public CTHOADON()
		{
			this._GIAY = default(EntityRef<GIAY>);
			this._HOADON = default(EntityRef<HOADON>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCTHD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaCTHD
		{
			get
			{
				return this._MaCTHD;
			}
			set
			{
				if ((this._MaCTHD != value))
				{
					this.OnMaCTHDChanging(value);
					this.SendPropertyChanging();
					this._MaCTHD = value;
					this.SendPropertyChanged("MaCTHD");
					this.OnMaCTHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", DbType="Int")]
		public System.Nullable<int> MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					if (this._HOADON.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._MaHoaDon = value;
					this.SendPropertyChanged("MaHoaDon");
					this.OnMaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGiay", DbType="Int")]
		public System.Nullable<int> MaGiay
		{
			get
			{
				return this._MaGiay;
			}
			set
			{
				if ((this._MaGiay != value))
				{
					if (this._GIAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGiayChanging(value);
					this.SendPropertyChanging();
					this._MaGiay = value;
					this.SendPropertyChanged("MaGiay");
					this.OnMaGiayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Float")]
		public System.Nullable<double> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAY_CTHOADON", Storage="_GIAY", ThisKey="MaGiay", OtherKey="MaGiay", IsForeignKey=true, DeleteRule="SET NULL")]
		public GIAY GIAY
		{
			get
			{
				return this._GIAY.Entity;
			}
			set
			{
				GIAY previousValue = this._GIAY.Entity;
				if (((previousValue != value) 
							|| (this._GIAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GIAY.Entity = null;
						previousValue.CTHOADONs.Remove(this);
					}
					this._GIAY.Entity = value;
					if ((value != null))
					{
						value.CTHOADONs.Add(this);
						this._MaGiay = value.MaGiay;
					}
					else
					{
						this._MaGiay = default(Nullable<int>);
					}
					this.SendPropertyChanged("GIAY");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_CTHOADON", Storage="_HOADON", ThisKey="MaHoaDon", OtherKey="MaHoaDon", IsForeignKey=true, DeleteRule="CASCADE")]
		public HOADON HOADON
		{
			get
			{
				return this._HOADON.Entity;
			}
			set
			{
				HOADON previousValue = this._HOADON.Entity;
				if (((previousValue != value) 
							|| (this._HOADON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOADON.Entity = null;
						previousValue.CTHOADONs.Remove(this);
					}
					this._HOADON.Entity = value;
					if ((value != null))
					{
						value.CTHOADONs.Add(this);
						this._MaHoaDon = value.MaHoaDon;
					}
					else
					{
						this._MaHoaDon = default(Nullable<int>);
					}
					this.SendPropertyChanged("HOADON");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GIAY")]
	public partial class GIAY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaGiay;
		
		private string _TenGiay;
		
		private string _MoTa;
		
		private System.Nullable<int> _MaGioiTinh;
		
		private string _HinhGiay;
		
		private System.Nullable<double> _GiaNhap;
		
		private System.Nullable<double> _GiaBan;
		
		private System.Nullable<int> _SLTon;
		
		private System.Nullable<int> _MaThuongHieu;
		
		private System.Nullable<int> _MaKieuDang;
		
		private System.Nullable<int> _MaLoaiGiay;
		
		private System.Nullable<int> _MaMau;
		
		private System.Nullable<int> _MaSize;
		
		private System.Nullable<int> _MaChatLieu;
		
		private EntitySet<CTHOADON> _CTHOADONs;
		
		private EntityRef<CHATLIEU> _CHATLIEU;
		
		private EntityRef<GIOITINH> _GIOITINH;
		
		private EntityRef<KIEUDANG> _KIEUDANG;
		
		private EntityRef<LOAIGIAY> _LOAIGIAY;
		
		private EntityRef<MAU> _MAU;
		
		private EntityRef<SIZE> _SIZE;
		
		private EntityRef<THUONGHIEU> _THUONGHIEU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGiayChanging(int value);
    partial void OnMaGiayChanged();
    partial void OnTenGiayChanging(string value);
    partial void OnTenGiayChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnMaGioiTinhChanging(System.Nullable<int> value);
    partial void OnMaGioiTinhChanged();
    partial void OnHinhGiayChanging(string value);
    partial void OnHinhGiayChanged();
    partial void OnGiaNhapChanging(System.Nullable<double> value);
    partial void OnGiaNhapChanged();
    partial void OnGiaBanChanging(System.Nullable<double> value);
    partial void OnGiaBanChanged();
    partial void OnSLTonChanging(System.Nullable<int> value);
    partial void OnSLTonChanged();
    partial void OnMaThuongHieuChanging(System.Nullable<int> value);
    partial void OnMaThuongHieuChanged();
    partial void OnMaKieuDangChanging(System.Nullable<int> value);
    partial void OnMaKieuDangChanged();
    partial void OnMaLoaiGiayChanging(System.Nullable<int> value);
    partial void OnMaLoaiGiayChanged();
    partial void OnMaMauChanging(System.Nullable<int> value);
    partial void OnMaMauChanged();
    partial void OnMaSizeChanging(System.Nullable<int> value);
    partial void OnMaSizeChanged();
    partial void OnMaChatLieuChanging(System.Nullable<int> value);
    partial void OnMaChatLieuChanged();
    #endregion
		
		public GIAY()
		{
			this._CTHOADONs = new EntitySet<CTHOADON>(new Action<CTHOADON>(this.attach_CTHOADONs), new Action<CTHOADON>(this.detach_CTHOADONs));
			this._CHATLIEU = default(EntityRef<CHATLIEU>);
			this._GIOITINH = default(EntityRef<GIOITINH>);
			this._KIEUDANG = default(EntityRef<KIEUDANG>);
			this._LOAIGIAY = default(EntityRef<LOAIGIAY>);
			this._MAU = default(EntityRef<MAU>);
			this._SIZE = default(EntityRef<SIZE>);
			this._THUONGHIEU = default(EntityRef<THUONGHIEU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGiay", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaGiay
		{
			get
			{
				return this._MaGiay;
			}
			set
			{
				if ((this._MaGiay != value))
				{
					this.OnMaGiayChanging(value);
					this.SendPropertyChanging();
					this._MaGiay = value;
					this.SendPropertyChanged("MaGiay");
					this.OnMaGiayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGiay", DbType="NVarChar(100)")]
		public string TenGiay
		{
			get
			{
				return this._TenGiay;
			}
			set
			{
				if ((this._TenGiay != value))
				{
					this.OnTenGiayChanging(value);
					this.SendPropertyChanging();
					this._TenGiay = value;
					this.SendPropertyChanged("TenGiay");
					this.OnTenGiayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(500)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGioiTinh", DbType="Int")]
		public System.Nullable<int> MaGioiTinh
		{
			get
			{
				return this._MaGioiTinh;
			}
			set
			{
				if ((this._MaGioiTinh != value))
				{
					if (this._GIOITINH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._MaGioiTinh = value;
					this.SendPropertyChanged("MaGioiTinh");
					this.OnMaGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhGiay", DbType="VarChar(100)")]
		public string HinhGiay
		{
			get
			{
				return this._HinhGiay;
			}
			set
			{
				if ((this._HinhGiay != value))
				{
					this.OnHinhGiayChanging(value);
					this.SendPropertyChanging();
					this._HinhGiay = value;
					this.SendPropertyChanged("HinhGiay");
					this.OnHinhGiayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaNhap", DbType="Float")]
		public System.Nullable<double> GiaNhap
		{
			get
			{
				return this._GiaNhap;
			}
			set
			{
				if ((this._GiaNhap != value))
				{
					this.OnGiaNhapChanging(value);
					this.SendPropertyChanging();
					this._GiaNhap = value;
					this.SendPropertyChanged("GiaNhap");
					this.OnGiaNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaBan", DbType="Float")]
		public System.Nullable<double> GiaBan
		{
			get
			{
				return this._GiaBan;
			}
			set
			{
				if ((this._GiaBan != value))
				{
					this.OnGiaBanChanging(value);
					this.SendPropertyChanging();
					this._GiaBan = value;
					this.SendPropertyChanged("GiaBan");
					this.OnGiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLTon", DbType="Int")]
		public System.Nullable<int> SLTon
		{
			get
			{
				return this._SLTon;
			}
			set
			{
				if ((this._SLTon != value))
				{
					this.OnSLTonChanging(value);
					this.SendPropertyChanging();
					this._SLTon = value;
					this.SendPropertyChanged("SLTon");
					this.OnSLTonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThuongHieu", DbType="Int")]
		public System.Nullable<int> MaThuongHieu
		{
			get
			{
				return this._MaThuongHieu;
			}
			set
			{
				if ((this._MaThuongHieu != value))
				{
					if (this._THUONGHIEU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaThuongHieuChanging(value);
					this.SendPropertyChanging();
					this._MaThuongHieu = value;
					this.SendPropertyChanged("MaThuongHieu");
					this.OnMaThuongHieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKieuDang", DbType="Int")]
		public System.Nullable<int> MaKieuDang
		{
			get
			{
				return this._MaKieuDang;
			}
			set
			{
				if ((this._MaKieuDang != value))
				{
					if (this._KIEUDANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKieuDangChanging(value);
					this.SendPropertyChanging();
					this._MaKieuDang = value;
					this.SendPropertyChanged("MaKieuDang");
					this.OnMaKieuDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiGiay", DbType="Int")]
		public System.Nullable<int> MaLoaiGiay
		{
			get
			{
				return this._MaLoaiGiay;
			}
			set
			{
				if ((this._MaLoaiGiay != value))
				{
					if (this._LOAIGIAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiGiayChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiGiay = value;
					this.SendPropertyChanged("MaLoaiGiay");
					this.OnMaLoaiGiayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMau", DbType="Int")]
		public System.Nullable<int> MaMau
		{
			get
			{
				return this._MaMau;
			}
			set
			{
				if ((this._MaMau != value))
				{
					if (this._MAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMauChanging(value);
					this.SendPropertyChanging();
					this._MaMau = value;
					this.SendPropertyChanged("MaMau");
					this.OnMaMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSize", DbType="Int")]
		public System.Nullable<int> MaSize
		{
			get
			{
				return this._MaSize;
			}
			set
			{
				if ((this._MaSize != value))
				{
					if (this._SIZE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSizeChanging(value);
					this.SendPropertyChanging();
					this._MaSize = value;
					this.SendPropertyChanged("MaSize");
					this.OnMaSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChatLieu", DbType="Int")]
		public System.Nullable<int> MaChatLieu
		{
			get
			{
				return this._MaChatLieu;
			}
			set
			{
				if ((this._MaChatLieu != value))
				{
					if (this._CHATLIEU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaChatLieuChanging(value);
					this.SendPropertyChanging();
					this._MaChatLieu = value;
					this.SendPropertyChanged("MaChatLieu");
					this.OnMaChatLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIAY_CTHOADON", Storage="_CTHOADONs", ThisKey="MaGiay", OtherKey="MaGiay")]
		public EntitySet<CTHOADON> CTHOADONs
		{
			get
			{
				return this._CTHOADONs;
			}
			set
			{
				this._CTHOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHATLIEU_GIAY", Storage="_CHATLIEU", ThisKey="MaChatLieu", OtherKey="MaChatLieu", IsForeignKey=true, DeleteRule="SET NULL")]
		public CHATLIEU CHATLIEU
		{
			get
			{
				return this._CHATLIEU.Entity;
			}
			set
			{
				CHATLIEU previousValue = this._CHATLIEU.Entity;
				if (((previousValue != value) 
							|| (this._CHATLIEU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHATLIEU.Entity = null;
						previousValue.GIAYs.Remove(this);
					}
					this._CHATLIEU.Entity = value;
					if ((value != null))
					{
						value.GIAYs.Add(this);
						this._MaChatLieu = value.MaChatLieu;
					}
					else
					{
						this._MaChatLieu = default(Nullable<int>);
					}
					this.SendPropertyChanged("CHATLIEU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIOITINH_GIAY", Storage="_GIOITINH", ThisKey="MaGioiTinh", OtherKey="MaGioiTinh", IsForeignKey=true)]
		public GIOITINH GIOITINH
		{
			get
			{
				return this._GIOITINH.Entity;
			}
			set
			{
				GIOITINH previousValue = this._GIOITINH.Entity;
				if (((previousValue != value) 
							|| (this._GIOITINH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GIOITINH.Entity = null;
						previousValue.GIAYs.Remove(this);
					}
					this._GIOITINH.Entity = value;
					if ((value != null))
					{
						value.GIAYs.Add(this);
						this._MaGioiTinh = value.MaGioiTinh;
					}
					else
					{
						this._MaGioiTinh = default(Nullable<int>);
					}
					this.SendPropertyChanged("GIOITINH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KIEUDANG_GIAY", Storage="_KIEUDANG", ThisKey="MaKieuDang", OtherKey="MaKieuDang", IsForeignKey=true, DeleteRule="SET NULL")]
		public KIEUDANG KIEUDANG
		{
			get
			{
				return this._KIEUDANG.Entity;
			}
			set
			{
				KIEUDANG previousValue = this._KIEUDANG.Entity;
				if (((previousValue != value) 
							|| (this._KIEUDANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KIEUDANG.Entity = null;
						previousValue.GIAYs.Remove(this);
					}
					this._KIEUDANG.Entity = value;
					if ((value != null))
					{
						value.GIAYs.Add(this);
						this._MaKieuDang = value.MaKieuDang;
					}
					else
					{
						this._MaKieuDang = default(Nullable<int>);
					}
					this.SendPropertyChanged("KIEUDANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIGIAY_GIAY", Storage="_LOAIGIAY", ThisKey="MaLoaiGiay", OtherKey="MaLoaiGiay", IsForeignKey=true, DeleteRule="SET NULL")]
		public LOAIGIAY LOAIGIAY
		{
			get
			{
				return this._LOAIGIAY.Entity;
			}
			set
			{
				LOAIGIAY previousValue = this._LOAIGIAY.Entity;
				if (((previousValue != value) 
							|| (this._LOAIGIAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIGIAY.Entity = null;
						previousValue.GIAYs.Remove(this);
					}
					this._LOAIGIAY.Entity = value;
					if ((value != null))
					{
						value.GIAYs.Add(this);
						this._MaLoaiGiay = value.MaLoaiGiay;
					}
					else
					{
						this._MaLoaiGiay = default(Nullable<int>);
					}
					this.SendPropertyChanged("LOAIGIAY");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAU_GIAY", Storage="_MAU", ThisKey="MaMau", OtherKey="MaMau", IsForeignKey=true, DeleteRule="SET NULL")]
		public MAU MAU
		{
			get
			{
				return this._MAU.Entity;
			}
			set
			{
				MAU previousValue = this._MAU.Entity;
				if (((previousValue != value) 
							|| (this._MAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MAU.Entity = null;
						previousValue.GIAYs.Remove(this);
					}
					this._MAU.Entity = value;
					if ((value != null))
					{
						value.GIAYs.Add(this);
						this._MaMau = value.MaMau;
					}
					else
					{
						this._MaMau = default(Nullable<int>);
					}
					this.SendPropertyChanged("MAU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SIZE_GIAY", Storage="_SIZE", ThisKey="MaSize", OtherKey="MaSize", IsForeignKey=true, DeleteRule="SET NULL")]
		public SIZE SIZE
		{
			get
			{
				return this._SIZE.Entity;
			}
			set
			{
				SIZE previousValue = this._SIZE.Entity;
				if (((previousValue != value) 
							|| (this._SIZE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SIZE.Entity = null;
						previousValue.GIAYs.Remove(this);
					}
					this._SIZE.Entity = value;
					if ((value != null))
					{
						value.GIAYs.Add(this);
						this._MaSize = value.MaSize;
					}
					else
					{
						this._MaSize = default(Nullable<int>);
					}
					this.SendPropertyChanged("SIZE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUONGHIEU_GIAY", Storage="_THUONGHIEU", ThisKey="MaThuongHieu", OtherKey="MaThuongHieu", IsForeignKey=true, DeleteRule="SET NULL")]
		public THUONGHIEU THUONGHIEU
		{
			get
			{
				return this._THUONGHIEU.Entity;
			}
			set
			{
				THUONGHIEU previousValue = this._THUONGHIEU.Entity;
				if (((previousValue != value) 
							|| (this._THUONGHIEU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THUONGHIEU.Entity = null;
						previousValue.GIAYs.Remove(this);
					}
					this._THUONGHIEU.Entity = value;
					if ((value != null))
					{
						value.GIAYs.Add(this);
						this._MaThuongHieu = value.MaThuongHieu;
					}
					else
					{
						this._MaThuongHieu = default(Nullable<int>);
					}
					this.SendPropertyChanged("THUONGHIEU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTHOADONs(CTHOADON entity)
		{
			this.SendPropertyChanging();
			entity.GIAY = this;
		}
		
		private void detach_CTHOADONs(CTHOADON entity)
		{
			this.SendPropertyChanging();
			entity.GIAY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GIOITINH")]
	public partial class GIOITINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaGioiTinh;
		
		private string _TenGioiTinh;
		
		private EntitySet<GIAY> _GIAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGioiTinhChanging(int value);
    partial void OnMaGioiTinhChanged();
    partial void OnTenGioiTinhChanging(string value);
    partial void OnTenGioiTinhChanged();
    #endregion
		
		public GIOITINH()
		{
			this._GIAYs = new EntitySet<GIAY>(new Action<GIAY>(this.attach_GIAYs), new Action<GIAY>(this.detach_GIAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGioiTinh", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaGioiTinh
		{
			get
			{
				return this._MaGioiTinh;
			}
			set
			{
				if ((this._MaGioiTinh != value))
				{
					this.OnMaGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._MaGioiTinh = value;
					this.SendPropertyChanged("MaGioiTinh");
					this.OnMaGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGioiTinh", DbType="NVarChar(10)")]
		public string TenGioiTinh
		{
			get
			{
				return this._TenGioiTinh;
			}
			set
			{
				if ((this._TenGioiTinh != value))
				{
					this.OnTenGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._TenGioiTinh = value;
					this.SendPropertyChanged("TenGioiTinh");
					this.OnTenGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIOITINH_GIAY", Storage="_GIAYs", ThisKey="MaGioiTinh", OtherKey="MaGioiTinh")]
		public EntitySet<GIAY> GIAYs
		{
			get
			{
				return this._GIAYs;
			}
			set
			{
				this._GIAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.GIOITINH = this;
		}
		
		private void detach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.GIOITINH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADON")]
	public partial class HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHoaDon;
		
		private System.Nullable<System.DateTime> _NgayLap;
		
		private System.Nullable<double> _TongTien;
		
		private System.Nullable<int> _MaTinhTrang;
		
		private System.Nullable<int> _MaKhachHang;
		
		private EntitySet<CTHOADON> _CTHOADONs;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
		private EntityRef<TINHTRANGDONHANG> _TINHTRANGDONHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoaDonChanging(int value);
    partial void OnMaHoaDonChanged();
    partial void OnNgayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapChanged();
    partial void OnTongTienChanging(System.Nullable<double> value);
    partial void OnTongTienChanged();
    partial void OnMaTinhTrangChanging(System.Nullable<int> value);
    partial void OnMaTinhTrangChanged();
    partial void OnMaKhachHangChanging(System.Nullable<int> value);
    partial void OnMaKhachHangChanged();
    #endregion
		
		public HOADON()
		{
			this._CTHOADONs = new EntitySet<CTHOADON>(new Action<CTHOADON>(this.attach_CTHOADONs), new Action<CTHOADON>(this.detach_CTHOADONs));
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			this._TINHTRANGDONHANG = default(EntityRef<TINHTRANGDONHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					this.OnMaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._MaHoaDon = value;
					this.SendPropertyChanged("MaHoaDon");
					this.OnMaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayLap
		{
			get
			{
				return this._NgayLap;
			}
			set
			{
				if ((this._NgayLap != value))
				{
					this.OnNgayLapChanging(value);
					this.SendPropertyChanging();
					this._NgayLap = value;
					this.SendPropertyChanged("NgayLap");
					this.OnNgayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Float")]
		public System.Nullable<double> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTinhTrang", DbType="Int")]
		public System.Nullable<int> MaTinhTrang
		{
			get
			{
				return this._MaTinhTrang;
			}
			set
			{
				if ((this._MaTinhTrang != value))
				{
					if (this._TINHTRANGDONHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._MaTinhTrang = value;
					this.SendPropertyChanged("MaTinhTrang");
					this.OnMaTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="Int")]
		public System.Nullable<int> MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_CTHOADON", Storage="_CTHOADONs", ThisKey="MaHoaDon", OtherKey="MaHoaDon")]
		public EntitySet<CTHOADON> CTHOADONs
		{
			get
			{
				return this._CTHOADONs;
			}
			set
			{
				this._CTHOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_HOADON", Storage="_KHACHHANG", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsForeignKey=true, DeleteRule="SET NULL")]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._MaKhachHang = value.MaKhachHang;
					}
					else
					{
						this._MaKhachHang = default(Nullable<int>);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TINHTRANGDONHANG_HOADON", Storage="_TINHTRANGDONHANG", ThisKey="MaTinhTrang", OtherKey="MaTinhTrang", IsForeignKey=true)]
		public TINHTRANGDONHANG TINHTRANGDONHANG
		{
			get
			{
				return this._TINHTRANGDONHANG.Entity;
			}
			set
			{
				TINHTRANGDONHANG previousValue = this._TINHTRANGDONHANG.Entity;
				if (((previousValue != value) 
							|| (this._TINHTRANGDONHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TINHTRANGDONHANG.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._TINHTRANGDONHANG.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._MaTinhTrang = value.MaTinhTrang;
					}
					else
					{
						this._MaTinhTrang = default(Nullable<int>);
					}
					this.SendPropertyChanged("TINHTRANGDONHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTHOADONs(CTHOADON entity)
		{
			this.SendPropertyChanging();
			entity.HOADON = this;
		}
		
		private void detach_CTHOADONs(CTHOADON entity)
		{
			this.SendPropertyChanging();
			entity.HOADON = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKhachHang;
		
		private string _TenKhachHang;
		
		private string _DiachiKH;
		
		private string _SDTKH;
		
		private string _MaTaiKhoanKH;
		
		private EntitySet<HOADON> _HOADONs;
		
		private EntityRef<TAIKHOANKH> _TAIKHOANKH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachHangChanging(int value);
    partial void OnMaKhachHangChanged();
    partial void OnTenKhachHangChanging(string value);
    partial void OnTenKhachHangChanged();
    partial void OnDiachiKHChanging(string value);
    partial void OnDiachiKHChanged();
    partial void OnSDTKHChanging(string value);
    partial void OnSDTKHChanged();
    partial void OnMaTaiKhoanKHChanging(string value);
    partial void OnMaTaiKhoanKHChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			this._TAIKHOANKH = default(EntityRef<TAIKHOANKH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhachHang", DbType="NVarChar(50)")]
		public string TenKhachHang
		{
			get
			{
				return this._TenKhachHang;
			}
			set
			{
				if ((this._TenKhachHang != value))
				{
					this.OnTenKhachHangChanging(value);
					this.SendPropertyChanging();
					this._TenKhachHang = value;
					this.SendPropertyChanged("TenKhachHang");
					this.OnTenKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiachiKH", DbType="NVarChar(200)")]
		public string DiachiKH
		{
			get
			{
				return this._DiachiKH;
			}
			set
			{
				if ((this._DiachiKH != value))
				{
					this.OnDiachiKHChanging(value);
					this.SendPropertyChanging();
					this._DiachiKH = value;
					this.SendPropertyChanged("DiachiKH");
					this.OnDiachiKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDTKH", DbType="VarChar(50)")]
		public string SDTKH
		{
			get
			{
				return this._SDTKH;
			}
			set
			{
				if ((this._SDTKH != value))
				{
					this.OnSDTKHChanging(value);
					this.SendPropertyChanging();
					this._SDTKH = value;
					this.SendPropertyChanged("SDTKH");
					this.OnSDTKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTaiKhoanKH", DbType="VarChar(50)")]
		public string MaTaiKhoanKH
		{
			get
			{
				return this._MaTaiKhoanKH;
			}
			set
			{
				if ((this._MaTaiKhoanKH != value))
				{
					if (this._TAIKHOANKH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTaiKhoanKHChanging(value);
					this.SendPropertyChanging();
					this._MaTaiKhoanKH = value;
					this.SendPropertyChanged("MaTaiKhoanKH");
					this.OnMaTaiKhoanKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_HOADON", Storage="_HOADONs", ThisKey="MaKhachHang", OtherKey="MaKhachHang")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOANKH_KHACHHANG", Storage="_TAIKHOANKH", ThisKey="MaTaiKhoanKH", OtherKey="MaTaiKhoanKH", IsForeignKey=true)]
		public TAIKHOANKH TAIKHOANKH
		{
			get
			{
				return this._TAIKHOANKH.Entity;
			}
			set
			{
				TAIKHOANKH previousValue = this._TAIKHOANKH.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOANKH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOANKH.Entity = null;
						previousValue.KHACHHANGs.Remove(this);
					}
					this._TAIKHOANKH.Entity = value;
					if ((value != null))
					{
						value.KHACHHANGs.Add(this);
						this._MaTaiKhoanKH = value.MaTaiKhoanKH;
					}
					else
					{
						this._MaTaiKhoanKH = default(string);
					}
					this.SendPropertyChanged("TAIKHOANKH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KIEUDANG")]
	public partial class KIEUDANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKieuDang;
		
		private string _TenKieuDang;
		
		private EntitySet<GIAY> _GIAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKieuDangChanging(int value);
    partial void OnMaKieuDangChanged();
    partial void OnTenKieuDangChanging(string value);
    partial void OnTenKieuDangChanged();
    #endregion
		
		public KIEUDANG()
		{
			this._GIAYs = new EntitySet<GIAY>(new Action<GIAY>(this.attach_GIAYs), new Action<GIAY>(this.detach_GIAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKieuDang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKieuDang
		{
			get
			{
				return this._MaKieuDang;
			}
			set
			{
				if ((this._MaKieuDang != value))
				{
					this.OnMaKieuDangChanging(value);
					this.SendPropertyChanging();
					this._MaKieuDang = value;
					this.SendPropertyChanged("MaKieuDang");
					this.OnMaKieuDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKieuDang", DbType="NVarChar(100)")]
		public string TenKieuDang
		{
			get
			{
				return this._TenKieuDang;
			}
			set
			{
				if ((this._TenKieuDang != value))
				{
					this.OnTenKieuDangChanging(value);
					this.SendPropertyChanging();
					this._TenKieuDang = value;
					this.SendPropertyChanged("TenKieuDang");
					this.OnTenKieuDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KIEUDANG_GIAY", Storage="_GIAYs", ThisKey="MaKieuDang", OtherKey="MaKieuDang")]
		public EntitySet<GIAY> GIAYs
		{
			get
			{
				return this._GIAYs;
			}
			set
			{
				this._GIAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.KIEUDANG = this;
		}
		
		private void detach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.KIEUDANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIGIAY")]
	public partial class LOAIGIAY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLoaiGiay;
		
		private string _TenLoaiGiay;
		
		private EntitySet<GIAY> _GIAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiGiayChanging(int value);
    partial void OnMaLoaiGiayChanged();
    partial void OnTenLoaiGiayChanging(string value);
    partial void OnTenLoaiGiayChanged();
    #endregion
		
		public LOAIGIAY()
		{
			this._GIAYs = new EntitySet<GIAY>(new Action<GIAY>(this.attach_GIAYs), new Action<GIAY>(this.detach_GIAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiGiay", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLoaiGiay
		{
			get
			{
				return this._MaLoaiGiay;
			}
			set
			{
				if ((this._MaLoaiGiay != value))
				{
					this.OnMaLoaiGiayChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiGiay = value;
					this.SendPropertyChanged("MaLoaiGiay");
					this.OnMaLoaiGiayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiGiay", DbType="NVarChar(100)")]
		public string TenLoaiGiay
		{
			get
			{
				return this._TenLoaiGiay;
			}
			set
			{
				if ((this._TenLoaiGiay != value))
				{
					this.OnTenLoaiGiayChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiGiay = value;
					this.SendPropertyChanged("TenLoaiGiay");
					this.OnTenLoaiGiayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIGIAY_GIAY", Storage="_GIAYs", ThisKey="MaLoaiGiay", OtherKey="MaLoaiGiay")]
		public EntitySet<GIAY> GIAYs
		{
			get
			{
				return this._GIAYs;
			}
			set
			{
				this._GIAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.LOAIGIAY = this;
		}
		
		private void detach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.LOAIGIAY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAU")]
	public partial class MAU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaMau;
		
		private string _TenMau;
		
		private EntitySet<GIAY> _GIAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMauChanging(int value);
    partial void OnMaMauChanged();
    partial void OnTenMauChanging(string value);
    partial void OnTenMauChanged();
    #endregion
		
		public MAU()
		{
			this._GIAYs = new EntitySet<GIAY>(new Action<GIAY>(this.attach_GIAYs), new Action<GIAY>(this.detach_GIAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMau", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaMau
		{
			get
			{
				return this._MaMau;
			}
			set
			{
				if ((this._MaMau != value))
				{
					this.OnMaMauChanging(value);
					this.SendPropertyChanging();
					this._MaMau = value;
					this.SendPropertyChanged("MaMau");
					this.OnMaMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMau", DbType="NVarChar(100)")]
		public string TenMau
		{
			get
			{
				return this._TenMau;
			}
			set
			{
				if ((this._TenMau != value))
				{
					this.OnTenMauChanging(value);
					this.SendPropertyChanging();
					this._TenMau = value;
					this.SendPropertyChanged("TenMau");
					this.OnTenMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAU_GIAY", Storage="_GIAYs", ThisKey="MaMau", OtherKey="MaMau")]
		public EntitySet<GIAY> GIAYs
		{
			get
			{
				return this._GIAYs;
			}
			set
			{
				this._GIAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.MAU = this;
		}
		
		private void detach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.MAU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QUANTRI")]
	public partial class QUANTRI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaQT;
		
		private string _TenQT;
		
		private string _DiachiQT;
		
		private string _SDTQT;
		
		private string _MaTaiKhoanKH;
		
		private EntityRef<TAIKHOANKH> _TAIKHOANKH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaQTChanging(int value);
    partial void OnMaQTChanged();
    partial void OnTenQTChanging(string value);
    partial void OnTenQTChanged();
    partial void OnDiachiQTChanging(string value);
    partial void OnDiachiQTChanged();
    partial void OnSDTQTChanging(string value);
    partial void OnSDTQTChanged();
    partial void OnMaTaiKhoanKHChanging(string value);
    partial void OnMaTaiKhoanKHChanged();
    #endregion
		
		public QUANTRI()
		{
			this._TAIKHOANKH = default(EntityRef<TAIKHOANKH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaQT
		{
			get
			{
				return this._MaQT;
			}
			set
			{
				if ((this._MaQT != value))
				{
					this.OnMaQTChanging(value);
					this.SendPropertyChanging();
					this._MaQT = value;
					this.SendPropertyChanged("MaQT");
					this.OnMaQTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQT", DbType="NVarChar(50)")]
		public string TenQT
		{
			get
			{
				return this._TenQT;
			}
			set
			{
				if ((this._TenQT != value))
				{
					this.OnTenQTChanging(value);
					this.SendPropertyChanging();
					this._TenQT = value;
					this.SendPropertyChanged("TenQT");
					this.OnTenQTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiachiQT", DbType="NVarChar(200)")]
		public string DiachiQT
		{
			get
			{
				return this._DiachiQT;
			}
			set
			{
				if ((this._DiachiQT != value))
				{
					this.OnDiachiQTChanging(value);
					this.SendPropertyChanging();
					this._DiachiQT = value;
					this.SendPropertyChanged("DiachiQT");
					this.OnDiachiQTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDTQT", DbType="VarChar(50)")]
		public string SDTQT
		{
			get
			{
				return this._SDTQT;
			}
			set
			{
				if ((this._SDTQT != value))
				{
					this.OnSDTQTChanging(value);
					this.SendPropertyChanging();
					this._SDTQT = value;
					this.SendPropertyChanged("SDTQT");
					this.OnSDTQTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTaiKhoanKH", DbType="VarChar(50)")]
		public string MaTaiKhoanKH
		{
			get
			{
				return this._MaTaiKhoanKH;
			}
			set
			{
				if ((this._MaTaiKhoanKH != value))
				{
					if (this._TAIKHOANKH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTaiKhoanKHChanging(value);
					this.SendPropertyChanging();
					this._MaTaiKhoanKH = value;
					this.SendPropertyChanged("MaTaiKhoanKH");
					this.OnMaTaiKhoanKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOANKH_QUANTRI", Storage="_TAIKHOANKH", ThisKey="MaTaiKhoanKH", OtherKey="MaTaiKhoanKH", IsForeignKey=true)]
		public TAIKHOANKH TAIKHOANKH
		{
			get
			{
				return this._TAIKHOANKH.Entity;
			}
			set
			{
				TAIKHOANKH previousValue = this._TAIKHOANKH.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOANKH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOANKH.Entity = null;
						previousValue.QUANTRIs.Remove(this);
					}
					this._TAIKHOANKH.Entity = value;
					if ((value != null))
					{
						value.QUANTRIs.Add(this);
						this._MaTaiKhoanKH = value.MaTaiKhoanKH;
					}
					else
					{
						this._MaTaiKhoanKH = default(string);
					}
					this.SendPropertyChanged("TAIKHOANKH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SIZE")]
	public partial class SIZE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaSize;
		
		private System.Nullable<int> _SoSize;
		
		private EntitySet<GIAY> _GIAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSizeChanging(int value);
    partial void OnMaSizeChanged();
    partial void OnSoSizeChanging(System.Nullable<int> value);
    partial void OnSoSizeChanged();
    #endregion
		
		public SIZE()
		{
			this._GIAYs = new EntitySet<GIAY>(new Action<GIAY>(this.attach_GIAYs), new Action<GIAY>(this.detach_GIAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSize", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaSize
		{
			get
			{
				return this._MaSize;
			}
			set
			{
				if ((this._MaSize != value))
				{
					this.OnMaSizeChanging(value);
					this.SendPropertyChanging();
					this._MaSize = value;
					this.SendPropertyChanged("MaSize");
					this.OnMaSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoSize", DbType="Int")]
		public System.Nullable<int> SoSize
		{
			get
			{
				return this._SoSize;
			}
			set
			{
				if ((this._SoSize != value))
				{
					this.OnSoSizeChanging(value);
					this.SendPropertyChanging();
					this._SoSize = value;
					this.SendPropertyChanged("SoSize");
					this.OnSoSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SIZE_GIAY", Storage="_GIAYs", ThisKey="MaSize", OtherKey="MaSize")]
		public EntitySet<GIAY> GIAYs
		{
			get
			{
				return this._GIAYs;
			}
			set
			{
				this._GIAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.SIZE = this;
		}
		
		private void detach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.SIZE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIKHOANKH")]
	public partial class TAIKHOANKH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTaiKhoanKH;
		
		private string _MatKhau;
		
		private string _Email;
		
		private System.Nullable<int> _MaVaiTro;
		
		private EntitySet<KHACHHANG> _KHACHHANGs;
		
		private EntitySet<QUANTRI> _QUANTRIs;
		
		private EntityRef<VAITRO> _VAITRO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTaiKhoanKHChanging(string value);
    partial void OnMaTaiKhoanKHChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnMaVaiTroChanging(System.Nullable<int> value);
    partial void OnMaVaiTroChanged();
    #endregion
		
		public TAIKHOANKH()
		{
			this._KHACHHANGs = new EntitySet<KHACHHANG>(new Action<KHACHHANG>(this.attach_KHACHHANGs), new Action<KHACHHANG>(this.detach_KHACHHANGs));
			this._QUANTRIs = new EntitySet<QUANTRI>(new Action<QUANTRI>(this.attach_QUANTRIs), new Action<QUANTRI>(this.detach_QUANTRIs));
			this._VAITRO = default(EntityRef<VAITRO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTaiKhoanKH", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTaiKhoanKH
		{
			get
			{
				return this._MaTaiKhoanKH;
			}
			set
			{
				if ((this._MaTaiKhoanKH != value))
				{
					this.OnMaTaiKhoanKHChanging(value);
					this.SendPropertyChanging();
					this._MaTaiKhoanKH = value;
					this.SendPropertyChanged("MaTaiKhoanKH");
					this.OnMaTaiKhoanKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVaiTro", DbType="Int")]
		public System.Nullable<int> MaVaiTro
		{
			get
			{
				return this._MaVaiTro;
			}
			set
			{
				if ((this._MaVaiTro != value))
				{
					if (this._VAITRO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaVaiTroChanging(value);
					this.SendPropertyChanging();
					this._MaVaiTro = value;
					this.SendPropertyChanged("MaVaiTro");
					this.OnMaVaiTroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOANKH_KHACHHANG", Storage="_KHACHHANGs", ThisKey="MaTaiKhoanKH", OtherKey="MaTaiKhoanKH")]
		public EntitySet<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this._KHACHHANGs;
			}
			set
			{
				this._KHACHHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOANKH_QUANTRI", Storage="_QUANTRIs", ThisKey="MaTaiKhoanKH", OtherKey="MaTaiKhoanKH")]
		public EntitySet<QUANTRI> QUANTRIs
		{
			get
			{
				return this._QUANTRIs;
			}
			set
			{
				this._QUANTRIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VAITRO_TAIKHOANKH", Storage="_VAITRO", ThisKey="MaVaiTro", OtherKey="MaVaiTro", IsForeignKey=true)]
		public VAITRO VAITRO
		{
			get
			{
				return this._VAITRO.Entity;
			}
			set
			{
				VAITRO previousValue = this._VAITRO.Entity;
				if (((previousValue != value) 
							|| (this._VAITRO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VAITRO.Entity = null;
						previousValue.TAIKHOANKHs.Remove(this);
					}
					this._VAITRO.Entity = value;
					if ((value != null))
					{
						value.TAIKHOANKHs.Add(this);
						this._MaVaiTro = value.MaVaiTro;
					}
					else
					{
						this._MaVaiTro = default(Nullable<int>);
					}
					this.SendPropertyChanged("VAITRO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOANKH = this;
		}
		
		private void detach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOANKH = null;
		}
		
		private void attach_QUANTRIs(QUANTRI entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOANKH = this;
		}
		
		private void detach_QUANTRIs(QUANTRI entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOANKH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THUONGHIEU")]
	public partial class THUONGHIEU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaThuongHieu;
		
		private string _TenThuongHieu;
		
		private EntitySet<GIAY> _GIAYs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThuongHieuChanging(int value);
    partial void OnMaThuongHieuChanged();
    partial void OnTenThuongHieuChanging(string value);
    partial void OnTenThuongHieuChanged();
    #endregion
		
		public THUONGHIEU()
		{
			this._GIAYs = new EntitySet<GIAY>(new Action<GIAY>(this.attach_GIAYs), new Action<GIAY>(this.detach_GIAYs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThuongHieu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaThuongHieu
		{
			get
			{
				return this._MaThuongHieu;
			}
			set
			{
				if ((this._MaThuongHieu != value))
				{
					this.OnMaThuongHieuChanging(value);
					this.SendPropertyChanging();
					this._MaThuongHieu = value;
					this.SendPropertyChanged("MaThuongHieu");
					this.OnMaThuongHieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThuongHieu", DbType="NVarChar(100)")]
		public string TenThuongHieu
		{
			get
			{
				return this._TenThuongHieu;
			}
			set
			{
				if ((this._TenThuongHieu != value))
				{
					this.OnTenThuongHieuChanging(value);
					this.SendPropertyChanging();
					this._TenThuongHieu = value;
					this.SendPropertyChanged("TenThuongHieu");
					this.OnTenThuongHieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUONGHIEU_GIAY", Storage="_GIAYs", ThisKey="MaThuongHieu", OtherKey="MaThuongHieu")]
		public EntitySet<GIAY> GIAYs
		{
			get
			{
				return this._GIAYs;
			}
			set
			{
				this._GIAYs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.THUONGHIEU = this;
		}
		
		private void detach_GIAYs(GIAY entity)
		{
			this.SendPropertyChanging();
			entity.THUONGHIEU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TINHTRANGDONHANG")]
	public partial class TINHTRANGDONHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTinhTrang;
		
		private string _TenTinhTrang;
		
		private EntitySet<HOADON> _HOADONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTinhTrangChanging(int value);
    partial void OnMaTinhTrangChanged();
    partial void OnTenTinhTrangChanging(string value);
    partial void OnTenTinhTrangChanged();
    #endregion
		
		public TINHTRANGDONHANG()
		{
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTinhTrang", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaTinhTrang
		{
			get
			{
				return this._MaTinhTrang;
			}
			set
			{
				if ((this._MaTinhTrang != value))
				{
					this.OnMaTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._MaTinhTrang = value;
					this.SendPropertyChanged("MaTinhTrang");
					this.OnMaTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTinhTrang", DbType="NVarChar(100)")]
		public string TenTinhTrang
		{
			get
			{
				return this._TenTinhTrang;
			}
			set
			{
				if ((this._TenTinhTrang != value))
				{
					this.OnTenTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TenTinhTrang = value;
					this.SendPropertyChanged("TenTinhTrang");
					this.OnTenTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TINHTRANGDONHANG_HOADON", Storage="_HOADONs", ThisKey="MaTinhTrang", OtherKey="MaTinhTrang")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.TINHTRANGDONHANG = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.TINHTRANGDONHANG = null;
		}
	}
}
#pragma warning restore 1591
